### ISSUE TITLE
Update to Ceylon 1.3.1

### ISSUE THREAD

**Issue by gavinking** [sgalles/ceylon-dddsample#2] opened 2016-11-20 23:01 UTC
Hi @sgalles, I'm trying to update the DDDSample to make use of new functionality of 1.3.1.

I think that I should be able to replace the module descriptor with this:

```ceylon
native("jvm")
module dddsample "1.0.0" {
	
	shared import javax.javaeeapi "7.0";
	shared import java.base "8";
	shared import ceylon.interop.java "1.3.1";
	shared import ceylon.json "1.3.1";
	
	// logging
	shared import org.slf4j.api "1.6.1";
	
}
```

And I think I should just be able to delete the `CeylonInit` portable extension, and just use `--static-metamodel` in `ceylon war` (or `ceylon swarm`).

However, when I tried this, I could not seem to get the app to deploy correctly on WildFly 10. It seems to get stuck waiting for the JMS queues to start. (There are no errors in the log.)

Any ideas?

**Comment by sgalles** [comment] 2016-11-21 22:38
Hi @gavinking 
I'll be glad to have a look at it (in a few days though as I'm quite busy at the moment)

**Comment by gavinking** [comment] 2016-11-21 22:49
OK, thanks.

**Comment by sgalles** [comment] 2016-11-24 21:04
@gavinking I don't know if you want to update DDD sample in my repos, or if you want to fork it, but for all pratical purpose you should have the right to push to my repos if needed

**Comment by sgalles** [comment] 2016-11-24 21:11
@gavinking that being said, don't hesitate to fork it in other GitHub account if you wish (your repos, or ceylon's repos) if you think it is useful

**Comment by gavinking** [comment] 2016-11-26 12:58
@sgalles Well I didn't want to push anything, because, like I said, the app never seems to start. It gets stuck waiting for JMS queues. I have no clue why.

**Comment by sgalles** [comment] 2016-11-26 22:11
OK @gavinking , so first step, I'm trying to change the bare minimum and make it work with :
* ceylon1.3.1
* static metamodel
* wildfly 9 (baby steps, when it works with 9, I'll try 10)

In this new branch https://github.com/sgalles/ceylon-dddsample/tree/ceylon1.3.1 I commited some modifications https://github.com/sgalles/ceylon-dddsample/commit/ef0ff7e4ee9dc7319e563fc6fa224c299e2a5254 to :
* compile with ceylon1.3.1 
* remove the CDI extension (anyway my boostrap code did not compile anymore with Ceylon1.3.1)
* added an `assert` to demonstrate that the ceylon metamodel isn't initialized when I need it.

And in particular, the problem shows up here
https://github.com/sgalles/ceylon-dddsample/blob/ef0ff7e4ee9dc7319e563fc6fa224c299e2a5254/source/dddsample/cargotracker/infrastructure/persistence/jpa/CeylonEnumValuesConverter.ceylon#L53
In a class that I use as a `javax.persistence.AttributeConverter` to manage the string conversion of my enums for JPA

When I package this code with Ceylon 1.3.1 :
* `ceylon compile`
*  `ceylon war dddsample/1.0.0 -R webapp --static-metamodel`
and when it is deployed in Wildfly 9, started with `standalone.bat -c standalone-full.xml` I get this exception at startup :
```
2016-11-26 22:43:21,182 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 67) MSC000001: Failed to start service jboss.persistenceunit."dddsample-1.0.0.war#ServletUnit": org.jboss.msc.service.StartException in service jboss.persistenceunit."dddsample-1.0.0.war#ServletUnit": ceylon.language.AssertionError "Assertion failed: No elements found for enums values. Is the metamodel initialized ?
	violated nonempty enums"
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:172)
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:117)
	at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:665)
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:182)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: ceylon.language.AssertionError "Assertion failed: No elements found for enums values. Is the metamodel initialized ?
	violated nonempty enums"
	at dddsample.cargotracker.infrastructure.persistence.jpa.CeylonEnumValuesConverter.<init>(CeylonEnumValuesConverter.ceylon:54)
	at dddsample.cargotracker.infrastructure.persistence.jpa.TransportStatusConverter.<init>(CeylonEnumValuesConverter.ceylon:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.hibernate.cfg.Configuration.instantiateAttributeConverter(Configuration.java:2682)
	at org.hibernate.cfg.Configuration.addAttributeConverter(Configuration.java:2673)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.buildHibernateConfiguration(EntityManagerFactoryBuilderImpl.java:1153)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:853)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850)
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:425)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:849)
	at org.jboss.as.jpa.hibernate4.TwoPhaseBootstrapImpl.build(TwoPhaseBootstrapImpl.java:44)
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:154)
	... 7 more

2016-11-26 22:43:21,196 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "dddsample-1.0.0.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.persistenceunit.\"dddsample-1.0.0.war#ServletUnit\"" => "org.jboss.msc.service.StartException in service jboss.persistenceunit.\"dddsample-1.0.0.war#ServletUnit\": ceylon.language.AssertionError \"Assertion failed: No elements found for enums values. Is the metamodel initialized ?
	violated nonempty enums\"
    Caused by: ceylon.language.AssertionError \"Assertion failed: No elements found for enums values. Is the metamodel initialized ?
	violated nonempty enums\""}}
2016-11-26 22:43:21,416 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 37) WFLYSRV0010: Deployed "dddsample-1.0.0.war" (runtime-name : "dddsample-1.0.0.war")
2016-11-26 22:43:21,421 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.persistenceunit."dddsample-1.0.0.war#ServletUnit": org.jboss.msc.service.StartException in service jboss.persistenceunit."dddsample-1.0.0.war#ServletUnit": ceylon.language.AssertionError "Assertion failed: No elements found for enums values. Is the metamodel initialized ?
	violated nonempty enums"

```
This used to work with the metamodel initialized via the CDI extension.
BTW for now I can't really reproduce your problem with JMS as I can't get to the point where my app is deployed (because of the metamodel error above)

*EDITED* : Same error for me on Wildfly 10

**Comment by gavinking** [comment] 2016-11-27 16:06
@FroMage, WDYT? This is a question for you, really?

**Comment by FroMage** [comment] 2016-11-28 16:13
I can reproduce. It could be that the class resources are not visible at this point. That'd suck. These are hard to debug too.

**Comment by FroMage** [comment] 2016-11-28 17:03
Ah, I have another issue which is that `ceylon war` does not respect dist-overrides and I have two versions of the dist modules :(

**Comment by FroMage** [comment] 2016-11-29 11:05
OK, I got that fixed, and now I have an issue about loading `ceylon.language.Object`, so there's progress. The previous error was likely due to having two language modules.

**Comment by FroMage** [comment] 2016-11-29 14:06
That's likely due to the fact that neither the static metamodel nor the module loader respect overrides, apparently :(

**Comment by FroMage** [comment] 2016-11-29 15:04
And it's not trivial to add overrides to the static metamodel because it's in the `model` module, which would need to move to the `module-resolver` module, but the static metamodel would pull in stuff from `model` :(

**Comment by FroMage** [comment] 2016-11-30 16:35
Aaand I wasted two days on this crazy assumption and moving `Overrides` out of the CMR for nothing, because I was wrong and `Overrides` are supposed to be applied to everything the CMR resolves. So the problem is elsewhere.

**Comment by FroMage** [comment] 2016-11-30 17:32
Pffff. That was likely due to the overrides missing 1.3.1->1.3.2 entries :(

**Comment by FroMage** [comment] 2016-11-30 17:37
And once I've fixed this, the static metamodel is correct, and initialised, and _still_ the enum list is empty :(

**Comment by FroMage** [comment] 2016-11-30 17:52
Well, I verified that it works with the static metamodel in `fat-jar`, so that means it's really specific to WildFly :(

**Comment by FroMage** [comment] 2016-11-30 18:09
Aha, the metamodel is not called, it's the `        if(is ClassOrInterface<Type> type){` test that fails.

**Comment by FroMage** [comment] 2016-11-30 18:10
It's a `dddsample.cargotracker.domain.model.cargo::TransportStatus&ceylon.language::Object`, quite uselessly and frustratingly.

**Comment by FroMage** [comment] 2016-11-30 18:16
Calling `caseValues<RoutingStatus&Object>()` works, but calling `caseValues<T&Object>()` fails, where `T==RoutingStatus`. But that even fails for `ceylon run`, so it's not at all WildFly specific.

**Comment by FroMage** [comment] 2016-11-30 18:17
Because I assume `RoutingStatus&Object` is done by the TC at compile-time, where `T&Object` is not simplified at run-time by `TypeDescriptor`.

**Comment by FroMage** [comment] 2016-11-30 18:21
If I fix the code that does the `&Object` it now deploys. So at least I've fixed all war and static metamodel bugs. Remains a potential issue to turn `T&Object` to `T` if `T` is an `Object` at run-time, in `TypeDescriptor`.

**Comment by FroMage** [comment] 2016-12-01 09:29
The funny thing is that even with the bugs in `ceylon war`, that modification is enough to make it deploy with Ceylon 1.3.1:

```diff
diff --git a/source/dddsample/cargotracker/infrastructure/persistence/jpa/CeylonEnumValuesConverter.ceylon b/source/dddsample/cargotracker/infrastructure/persistence/jpa/CeylonEnumValuesConverter.ceylon
index 54e8975..0cf9c4b 100644
--- a/source/dddsample/cargotracker/infrastructure/persistence/jpa/CeylonEnumValuesConverter.ceylon
+++ b/source/dddsample/cargotracker/infrastructure/persistence/jpa/CeylonEnumValuesConverter.ceylon
@@ -45,10 +45,10 @@ shared class HandlingEventTypeConverter()
                satisfies AttributeConverter<HandlingEventType, JString> {}
 
 
-shared class CeylonEnumValuesConverter<EnumValue>() satisfies AttributeConverter<EnumValue, JString> 
+shared class CeylonEnumValuesConverter<EnumValue>() satisfies AttributeConverter<EnumValue, JString> given EnumValue satisfies Object
                {
        
-       value enums = caseValues<EnumValue&Object>();
+       value enums = caseValues<EnumValue>();
        
```

**Comment by sgalles** [comment] 2016-12-01 12:27
Excellent @FroMage ! I guess the `&Object` was a leftover of an experiment of mine in this code.
Cool, I'm now able to continue the integration with Ceylon 1.3.1.

**Comment by sgalles** [comment] 2016-12-01 22:44
So, now with this code https://github.com/sgalles/ceylon-dddsample/commit/dae5f86421be41c4492e49bbbc70dc01fb0585fa 
* it works on Wildfly 9
* it fails on Wildfly 10 with a JMS error. That's progress.

**Comment by sgalles** [comment] 2016-12-01 22:59
So, with @gavinking 's cleaned up `module.ceylon` https://github.com/sgalles/ceylon-dddsample/commit/533e1e91eee18b0b2cfe1910e03917736f1c3fee same situation.
* it works on Wildfly 9
* it fails on Wildfly 10 with a JMS error.
```
  "WFLYCTL0412: Required services that are not installed:" => ["jboss.ra.deployer.\"jmsra.rar\""],
```

**Comment by sgalles** [comment] 2016-12-01 23:13
Ah...it must have something to do with this :
```
diff wildfly-9.0.0.Final/standalone/configuration/standalone-full.xml wildfly-10.1.0.Final/standalone/configuration/standalone-full.xml
```

```diff
<                 <resource-adapter-ref resource-adapter-name="${ejb.resource-adapter-name:hornetq-ra.rar}"/>
---
>                 <resource-adapter-ref resource-adapter-name="${ejb.resource-adapter-name:activemq-ra.rar}"/>

```

**Comment by sgalles** [comment] 2016-12-01 23:58
OK, @gavinking with https://github.com/sgalles/ceylon-dddsample/commit/c0f44ad73b935b7af7236634c91c74ae594b6249 the branch works now with Wildfly 10.1 (with JMS).
I'll update the readme for Ceylon 1.3.1 and I'll merge on master an other day

**Comment by gavinking** [comment] 2016-12-02 07:08
OK, great! I'll try it out.

**Comment by sgalles** [comment] 2016-12-02 21:54
merged

**Closed as completed by sgalles** 2016-12-02 21:54 UTC

**Comment by gavinking** [comment] 2016-12-08 14:40
@sgalles I'm still having trouble running it.

I get:

```
15:39:22,877 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-8) MSC000001: Failed to start service jboss.deployment.unit."dddsample-1.0.0.war".PARSE: org.jboss.msc.service.StartException in service jboss.deployment.unit."dddsample-1.0.0.war".PARSE: WFLYSRV0153: Failed to process phase PARSE of deployment "dddsample-1.0.0.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:154)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.msc.service.ServiceNotFoundException: Service service jboss.ejb.default-resource-adapter-name-service not found
	at org.jboss.msc.service.ServiceContainerImpl.getRequiredService(ServiceContainerImpl.java:669)
	at org.jboss.as.ejb3.deployment.processors.MessageDrivenComponentDescriptionFactory.getDefaultResourceAdapterName(MessageDrivenComponentDescriptionFactory.java:274)
	at org.jboss.as.ejb3.deployment.processors.MessageDrivenComponentDescriptionFactory.processMessageBeans(MessageDrivenComponentDescriptionFactory.java:154)
	at org.jboss.as.ejb3.deployment.processors.MessageDrivenComponentDescriptionFactory.processAnnotations(MessageDrivenComponentDescriptionFactory.java:81)
	at org.jboss.as.ejb3.deployment.processors.AnnotatedEJBComponentDescriptionDeploymentUnitProcessor.processAnnotations(AnnotatedEJBComponentDescriptionDeploymentUnitProcessor.java:57)
	at org.jboss.as.ejb3.deployment.processors.AbstractDeploymentUnitProcessor.deploy(AbstractDeploymentUnitProcessor.java:76)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	... 5 more

15:39:22,880 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "dddsample-1.0.0.war")]) - failure description: {
    "WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"dddsample-1.0.0.war\".PARSE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"dddsample-1.0.0.war\".PARSE: WFLYSRV0153: Failed to process phase PARSE of deployment \"dddsample-1.0.0.war\"
    Caused by: org.jboss.msc.service.ServiceNotFoundException: Service service jboss.ejb.default-resource-adapter-name-service not found"},
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.deployment.unit.\"dddsample-1.0.0.war\".PARSE"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
}
```

**Comment by gavinking** [comment] 2016-12-08 14:41
This is on WildFly Full 10.1.0.Final, running `standalone.sh`.

**Comment by sgalles** [comment] 2016-12-08 16:25
Did you use `standalone.sh -c standalone-full.xml` ?

**Comment by gavinking** [comment] 2016-12-08 16:56
Oh, yes, sure, that's it, it's working now!
